info:
  title: test
  version: 0.0.1
  license:
    name: MIT
  contact: {}
openapi: 3.0.0
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    TestResponse:
      properties:
        TestUpperCamel:
          type: string
        testLowerCamel:
          type: string
        _embedded:
          properties:
            testNestedProperty:
              properties:
                _links:
                  properties: { self: { $ref: '#/components/schemas/HalLink' } }
                  required: [self]
                  type: object
                firstNameKana:
                  type: string
          required:
            - testNestedProperty
    HalLink:
      description: 'A single HAL link'
      properties:
        href:
          type: string
          description: 'Target of the link'
        type:
          type: string
          description: 'Content-type of the target resource'
        templated:
          type: boolean
          description: 'If set to true, the href should be interpeted as a URI-Template (RFC6570).'
        title:
          type: string
          description: 'Human readable title for the link'
        hreflang:
          type: string
          description: "Language of the target resource, such as 'en-CA'."
        hints:
          $ref: '#/components/schemas/LinkHints'
          description: 'Link hints, as defined in draft-nottingham-link-hint'
      required:
        - href
      type: object
      additionalProperties: false
    LinkHintFormats:
      description: 'A supported format, indexed by media type'
      type: object
      additionalProperties:
        properties:
          deprecated:
            type: boolean
            description: "If set to true, it indicates that this format is\ndeprecated"
          links:
            properties: {}
            additionalProperties:
              $ref: '#/components/schemas/HalLink'
            type: object
            description: "Relevant links to the format.\n\nMainly this could contain a 'profile' or 'describedby'\nlink. These both describe a schema for the format"
        type: object
paths:
  /hoge:
    get:
      operationId: Hoge
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
      parameters:
        - in: query
          name: camelCase
          required: false
          schema:
            format: double
            type: number
  /fuga:
    post:
      operationId: Fuga
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                TestUpperCamel:
                  type: string
                testLowerCamel:
                  type: string
                _embedded:
                  properties:
                    testNestedProperty:
                      properties:
                        _links:
                          properties:
                            { self: { $ref: '#/components/schemas/HalLink' } }
                          required: [self]
                          type: object
                        firstNameKana:
                          type: string
                foo:
                  type: string
                bar:
                  type: integer
                baz: # ファイル
                  type: string
                  format: binary
      responses:
        '200':
          description: ok
  /piyo:
    post:
      operationId: Piyo
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
  /users/{userId}:
    get:
      operationId: GetUser
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
  /foo:
    post:
      operationId: Foo
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    properties:
                      testNestedProperty:
                        properties:
                          _embedded:
                            properties:
                              TestNestedProperty2:
                                type: string
                          _links:
                            properties:
                              { self: { $ref: '#/components/schemas/HalLink' } }
                            required: [self]
                            type: object
                          firstNameKana:
                            type: string
                  profile:
                    $ref: '#/components/schemas/TestResponse'
                  action:
                    $ref: '#/components/schemas/TestResponse'
