components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    TestResponse:
      properties:
        _test_upper_camel:
          type: string
        test_lower_camel:
          type: string
        _embedded:
          properties:
            test_nested_property:
              properties:
                _links:
                  properties:
                    self:
                      $ref: '#/components/schemas/HalLink'
                  required:
                    - self
                  type: object
                first_name_kana:
                  type: string
          required:
            - test_nested_property
    HalLink:
      description: A single HAL link
      properties:
        href:
          type: string
          description: Target of the link
        type:
          type: string
          description: Content-type of the target resource
        templated:
          type: boolean
          description: >-
            If set to true, the href should be interpeted as a URI-Template
            (RFC6570).
        title:
          type: string
          description: Human readable title for the link
        hreflang:
          type: string
          description: Language of the target resource, such as 'en-CA'.
        hints:
          $ref: '#/components/schemas/LinkHints'
          description: Link hints, as defined in draft-nottingham-link-hint
      required:
        - href
      type: object
      additionalProperties: false
    LinkHintFormats:
      description: A supported format, indexed by media type
      type: object
      additionalProperties:
        properties:
          deprecated:
            type: boolean
            description: |-
              If set to true, it indicates that this format is
              deprecated
          links:
            properties: {}
            additionalProperties:
              $ref: '#/components/schemas/HalLink'
            type: object
            description: |-
              Relevant links to the format.

              Mainly this could contain a 'profile' or 'describedby'
              link. These both describe a schema for the format
        type: object
